name: Validation and Tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  UnitTests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MySQL
      uses: ankane/setup-mysql@v1
      with:
        mysql-version: 8.0
        database: tests
    - name: Run tests 
      run: xcodebuild -project OHMySQL.xcodeproj -scheme "OHMySQLTests" -parallel-testing-enabled NO -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" test \
        USER_NAME='root' \
        USER_PASSWORD='' \
        DB_NAME='tests' \
        DB_HOST='localhost' \
        DB_PORT='3306' \
        DB_SOCKET='/tmp/mysql.sock' | xcpretty
  CocoaPodsValidation:
    runs-on: macos-latest
    steps:
    - name: Cocoapods
      run: pod lib lint --allow-warnings
